remote_theme: mmistakes/minimal-mistakes

title: "Clémence Perrin"
name: "Clémence Perrin"
description: "PhD candidate - Optimization of PV and BESS systems"
url: "https://clemenceperrin.github.io"
baseurl: ""
repository: "clemenceperrin/clemenceperrin.github.io"
locale: "en-US"
minimal_mistakes_skin: "default"

author:
  name: "Clémence Perrin"
  avatar: "profile.png"          # → assets/images/profile.png
  bio: "Second year PhD candidate at Mines Paris and SunMind (Vinci Concessions)"
  employer: "Mines Paris - PSL / SunMind - Vinci Concessions"
  email: "clemence.perrin@minesparis.psl.eu"
  linkedin: "https://www.linkedin.com/in/clemence-perrin-b5263a17b"

# Par défaut : profil auteur visible partout
defaults:
  - scope:
      path: ""
    values:
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache   # requis par Minimal Mistakes

collections:
  publications:
    output: true
  talks:
    output: true
  portfolio:
    output: true
